import { Directive } from './types';

export const actProposals: Directive[] = [
  {
    id: 'ap1',
    title: 'Projekt ustawy o zmianie ustawy o ochronie danych osobowych i prywatności cyfrowej',
    creationDate: '2023-10-26',
    description: 'Projekt ma na celu kompleksowe dostosowanie polskiego systemu prawnego do wymogów wynikających z dynamicznego rozwoju technologii cyfrowych oraz zacieśnienie ochrony praw obywateli w zakresie prywatności w Internecie. Wprowadza nowe mechanizmy nadzoru nad podmiotami przetwarzającymi dane oraz zwiększa sankcje za ich naruszenie, ze szczególnym uwzględnieniem ochrony danych dzieci i młodzieży.',
    tags: ['ochrona danych', 'cyfryzacja', 'prywatność', 'technologia'],
    fileLink: '/files/projekt_RODO_PL.pdf',
    signaturesCollected: 38765,
  },
  {
    id: 'ap2',
    title: 'Projekt ustawy o wspieraniu odnawialnych źródeł energii i transformacji energetycznej',
    creationDate: '2023-09-15',
    description: 'Propozycja ma kluczowe znaczenie dla realizacji celów klimatycznych Polski i Unii Europejskiej. Wprowadza nowe preferencje inwestycyjne dla farm wiatrowych i fotowoltaicznych, ułatwia procesy administracyjne dla prosumentów oraz tworzy fundusz innowacji na rzecz magazynowania energii. Oczekuje się, że ustawa znacząco przyspieszy dekarbonizację polskiej gospodarki i zwiększy bezpieczeństwo energetyczne kraju.',
    tags: ['energia', 'środowisko', 'OZE', 'ekologia', 'klimat'],
    fileLink: '/files/projekt_OZE_transformacja.pdf',
    signaturesCollected: 72109,
  },
  {
    id: 'ap3',
    title: 'Projekt ustawy o zmianie Kodeksu pracy w zakresie równowagi między życiem zawodowym a prywatnym',
    creationDate: '2023-08-01',
    description: 'W odpowiedzi na zmieniające się potrzeby rynku pracy i oczekiwania pracowników, projekt wprowadza elastyczne formy zatrudnienia, w tym prawo do pracy zdalnej na wniosek pracownika oraz możliwość wnioskowania o elastyczny czas pracy. Zwiększa również uprawnienia rodziców do korzystania z urlopów opiekuńczych i wprowadza dodatkowe przerwy na regenerację dla pracowników umysłowych. Celem jest poprawa jakości życia i dobrostanu pracowników.',
    tags: ['prawo pracy', 'praca zdalna', 'work-life balance', 'socjal'],
    fileLink: '/files/projekt_kodeks_pracy_balans.pdf',
    signaturesCollected: 45321,
  },
  {
    id: 'ap4',
    title: 'Projekt ustawy o ułatwieniach w dostępie do usług cyfrowych dla obywateli',
    creationDate: '2023-07-20',
    description: 'Celem projektu jest usunięcie barier administracyjnych i technologicznych w dostępie do e-usług publicznych. Przewiduje wprowadzenie jednego, centralnego portalu usług publicznych, standaryzację interfejsów użytkownika oraz zapewnienie bezpłatnego wsparcia technicznego dla osób starszych i mniej zaawansowanych cyfrowo. Ma to przyczynić się do cyfrowego włączenia wszystkich grup społecznych.',
    tags: ['dostępność', 'cyfryzacja', 'e-usługi', 'administracja'],
    fileLink: '/files/projekt_e_uslugi_dostep.pdf',
    signaturesCollected: 21987,
  },
  {
    id: 'ap5',
    title: 'Projekt ustawy o rozwoju infrastruktury ładowania pojazdów elektrycznych i wodorowych',
    creationDate: '2023-06-01',
    description: 'Wspieranie rozwoju zrównoważonego transportu jest priorytetem. Ustawa przewiduje znaczące uproszczenie procedur budowy stacji ładowania oraz wprowadzenie preferencyjnych stawek za energię dla użytkowników pojazdów zeroemisyjnych. Zakłada również program dopłat do zakupu publicznych i prywatnych punktów ładowania, co ma zlikwidować bariery w rozwoju elektromobilności i wodoru.',
    tags: ['transport', 'ekologia', 'elektromobilność', 'wodór', 'infrastruktura'],
    fileLink: '/files/projekt_infrastruktura_EV.pdf',
    signaturesCollected: 61054,
  },
  {
    id: 'ap6',
    title: 'Projekt ustawy o wspieraniu lokalnych społeczności i inicjatyw obywatelskich',
    creationDate: '2023-05-10',
    description: 'Ustawa ma na celu wzmocnienie roli samorządów lokalnych i organizacji pozarządowych poprzez zwiększenie ich autonomii finansowej oraz uproszczenie zasad aplikowania o środki publiczne na projekty społeczne i kulturalne. Wprowadza również mechanizmy konsultacji społecznych i budżetu obywatelskiego jako stałe elementy zarządzania lokalnego. Ma to aktywizować obywateli i rozwijać kapitał społeczny.',
    tags: ['społeczeństwo', 'samorząd', 'inicjatywy obywatelskie', 'NGO'],
    fileLink: '/files/projekt_inicjatywy_obywatelskie.pdf',
    signaturesCollected: 51234,
  },
];